### ISSUE TITLE
Name clash with pypi package aspy

### ISSUE THREAD

**Issue by jayvdb** [asottile/aspy.yaml#28]
Just fyi, https://pypi.org/project/aspy/ has been registered by another project.

c93f2de here is 2014, while their first commit was September 2018.

I'm currently packaging aspy.yaml for openSUSE and the other dependencies of https://build.opensuse.org/package/show/home:jayvdb:tox/python-pre-commit, and was just checking because it isnt the first time a namespace caused problems.  https://github.com/asottile/aspy.refactor_imports also looks quite useful, so that would mean we need to create an 'extra' package for the namespace dir and its `__init__` , or make one package dependent on the other even if not strictly true. e.g. the fictitious [`jaraco.base`](https://build.opensuse.org/package/view_file/devel:languages:python/python-jaraco.packaging/python-jaraco.base.spec?expand=1) package.

As another aside, I noticed most of your packages sdist on PyPI do not include tests.  That means I need to use the GitHub archive instead of the PyPI sdist for packaging, which is a bit annoying because the packaging tools (py2pack) dont automatically fetch new releases from GitHub.  Not an immediate concern for the initial packaging, but definitely helpful to include them as new releases are cut.

**Comment by asottile** [comment]
For the `__init__` problem I'd just package for python 3 only and drop the file

Shame about the namespaces :S I don't know if pypi has a procedure for fixing this 

As for tests, yeah that's intentional, they would take up a namespace which I wouldn't own and including them in the package breaks other things. The github tgz should be sufficient (it's what I build my packages from)

**Comment by jayvdb** [comment]
Raised https://gitlab.com/alantrick/aspy/issues/1 over there.  Enjoy. ;-)

**Comment by asottile** [comment]
<3

**Comment by jayvdb** [comment]
For the tests, they should be shipped in the sdist using MANIFEST.in , and thus do not have a namespace and do not get installed.  They are just extra files in the sdist, in a directory, and we configure the test runner to look there.

**Comment by jayvdb** [comment]
Longer blurbs/discussion about tests & sdists at https://github.com/ottoyiu/django-cors-headers/issues/369 and https://github.com/tox-dev/tox-travis/issues/120 .  If you still dont want to, that is fine, I'll work around it, and maybe eventually improve the tools to make the problem disappear.

**Comment by asottile** [comment]
in the past I've just waited for setuptools to automatically do these things (LICENSE / README / etc.) -- I'd rather wait and see if something comes along for tests as well :)

**Comment by jayvdb** [comment]
There is magic in the very latest setuptools for including the LICENSE automatically , but not the tests , and I doubt that will happen any time soon as setuptools doesnt want to be trying to find the tests which it mostly leaves to `unittest` to do.  OTOH, license files are very important and very easy, so it was done (but not without objections iirc)

**Comment by asottile** [comment]
since there's nothing to really do here I'm closing -- thanks for bringing it to my attention!
